name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read # for checkout

env:
  HUSKY: 0 # don't run husky hooks like commit-lint

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: ./yarn.lock

      - name: Install dependencies
        run: yarn install

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: |
          yarn audit signatures
          npm audit signatures

      - name: Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn semantic-release
